# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimws', '0010_auto_20160506_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='phplib',
            name='name_next_os',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
