# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimws', '0011_phplib_name_stretch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phplib',
            name='name_next_os',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
