# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimws', '0014_phplibs_name_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phplib',
            name='name_next_os',
        ),
    ]
