from __future__ import absolute_import
import uuid
from celery import shared_task, Task
import json
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
import os
import random
import string
import crypt
from django.conf import settings
import requests
import platform
from sitesmanagement.models import VirtualMachine, HostNetworkConfig


class PlatformsAPINotWorkingException(Exception):
    pass


class PlatformsAPIInputException(Exception):
    pass


def get_api_secret():
    if platform.system() == 'Darwin':
        from passlib.hash import sha512_crypt
        return sha512_crypt.encrypt(settings.PLATFORMS_API_TOKEN, rounds=5000,
                                    implicit_rounds=True)  # Salt autogenerated
    return crypt.crypt(settings.PLATFORMS_API_TOKEN, "$6$"+''.join(random.sample(string.hexdigits, 16)))


def get_api_username():
    return settings.PLATFORMS_API_USERNAME


def on_vm_api_failure(request, response):
        subject = "MWS3: Platform's VM API ERROR"
        message = "An error was returned when sending a request to Platform's VM API.\n\n The request was: \n %s \n\n " \
                  "The answer was: \n %s" % (request, response)
        from_email = settings.EMAIL_MWS3_SUPPORT
        recipient_list = (settings.EMAIL_MWS3_SUPPORT, )
        send_mail(subject, message, from_email, recipient_list, fail_silently=False)
        return False # TODO raise exception? and log it in the logger


class TaskWithFailure(Task):
    abstract = True

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        subject = "MWS3: Platform's VM API ERROR"
        message = "An error happened when trying to communicate with Platform's VM API.\n The task id is " \
                  "%s. \n\n The parameters passed to the task were: %s \n\n " \
                  "The traceback is: \n %s" % (task_id, args, einfo)
        from_email = settings.EMAIL_MWS3_SUPPORT
        recipient_list = (settings.EMAIL_MWS3_SUPPORT, )
        send_mail(subject, message, from_email, recipient_list, fail_silently=False) # TODO raise exception? and log it in the logger


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def new_site_primary_vm(vm):
    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'create',
        'ip': vm.ipv4,
        'hostname': vm.hostname,
    }
    headers = {'Content-type': 'application/json'}

    if settings.OS_VERSION_VMAPI:
        json_object['os'] = settings.OS_VERSION_VMAPI

    try:
        response = json.loads(requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json",
                                            data=json.dumps(json_object), headers=headers).text)
    except Exception as e:
        raise new_site_primary_vm.retry(exc=e)

    if response['result'] == 'Success':
        vm.name = response['vmid']
        vm.status = 'installing'
        vm.save()
        return install_vm(vm)
    else:
        return on_vm_api_failure(json.dumps(json_object), response)


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def install_vm(vm):
    from apimws.models import AnsibleConfiguration
    AnsibleConfiguration.objects.create(vm=vm, key='os', value=json.dumps(settings.OS_VERSION))

    f = open(os.path.join(settings.BASE_DIR, 'apimws/debian_preseed.txt'), 'r')
    profile = f.read()
    f.close()

    from apimws.views import post_installation
    late_commands = [
        "mkdir -p /target/root/.ssh",
        "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6H3DRdUPejq6JRLBFNG4S0y/vqrTVQZBQMLeMcMjCctgpdkXF54/6yzmVOtsqoaeCKQZhlFWbP1CnBVBAnU6nZU7zlh7flMT3RfxkCCOmE7Pg85EaY04R2rKymPsUGaN94J7mzNBN9NP+UuCtWfPHQ5jW/FJvfTDimcjAvuvnSIrlcetSlAam6lmbdj660TOeSoWJD0myWu9BaRGNrjpRellNuomk00YvHkSBYjo0zRY1FHg/x1wie/mNnVEW7AvELYhe/+u3PRYzKaZcQ07ETfCdtwBgWTI+GvNkAnYSFTUd0nvYdkhCmA81KpwKwlctm4BXgA7tMr2ZBLGpcg3R mcv21@pick' >/target/root/.ssh/authorized_keys",
        "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCerKj8UJ4F6njySBpvRJWnH2A5KQopP+DO8aiRGeQkRmCCorKdmX8q79anpWmQkuxdqEXlCOEezOToFC992akTolkjCT0VPYWd5ZuIvvzwwe66vmqMXN1m7wfFHgtLAqDkF+KK94mQnmAh8HGL5WL3BGl+w8VaXxnfIUYpuzYdf0CZ3mET1lYNAal9cU4R4D1FBflmxSIWJKwrMrfHiXo+YIwyQvH21ZNAeEvEV4E9EgwkF1HjkVs7KUCxwjya652xbJWxQMcxflK8T0TY9fq6GWbbWatWY6J40wN7dqp+WgWjGyOrqDc3AUeJ37/sSqmJ7B/SBemPNId27I3EbJ1V bjh21@wraith' >>/target/root/.ssh/authorized_keys",
        "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDY8qT0ucAal95O6XpDq7uhNT+Fal3q+DPB2wBiUXtSjgCuWZFYeoKkR7rq97MM/tCyaW4ItCfWH1QTLsx1FOOTyfMiM9vDqpFJuDVzI/5pwOJVZYu27zxeWc1Dqa+ReabwqizL2kCxtvCx9bwRbUTFnfhXxb9y4bEHmkBHfp59Z6zJHr5/OTDsBioFUQkcQucpJB+fD0QRxCqk5xDIaiFI/xEVr4WhRkj7CWX4IYAn/gvOgNTrcunseYeIKC7V/9SB5bbKfFMMiJz8PW3bOJp5kDPZ4RA+AiVHguQ2geniryfsxlM78AHkQJ5b7arx7KgAFWR+kh5+9c32NQbPpj/D amc203' >>/target/root/.ssh/authorized_keys",
        "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAZURi9pqzIO/u92JSBdAKAfQAgEqCNBydHKvsMOQa9IdMxyjNP83ubO+KxQ7RLEF2BFUmCeFPG6tz+ZQY9tgaRIfiujCf8+rr2Seg5vDPlHOJFF0WZYEDUgf+KwrXfv8d3DfSgX77A/IGYNHfL6ASar64XbUBpXA/AuldEqDfRAYM+YyK7dD50kc7fH+sM2izeF6NmNQFvewkNqbov2j26knzcG4yBMRLrviUmniSwyfv/HIoj/nM/nV7TUgguCSgzvyU9C1dR+LRuc1YbcvxUkX7Ff9/cJ9TRsWaPERk+/hWQb0TiiWLLM7F5n6X6lyv+CVZtsz7N+PgVNa83tRDPog8lDc6jYkIFA2G7u6dZi/TbrAxL3CfkMqhl0AL5a56eELQLs/wIHBDqPfZzvUEXe07m/HrxN0lJCY9GiIHk/xKStL4XqMgCY/yu6gBGe4u0tM9xa/SNEbd0B+DHGzEabGpyRu6n9k9ULAfZMZoUnRswUZFpml2VICw5JaFzPuJI8Gh9RMDBBp4grAtGG2/a2pvNh8Lr5qCXlpbraCM/NboVLwJl+021V5Sgzh0BALssMcLzoJHcck0D7Paou2QatpIMVm/hWNiVJ5qoF1zjDdHRKAzMKP+hdiagrR1s+ns2FQ6tTW5bfyrUm3j5RoYh8TyXPh9G2t5+GhaPRxZtw== mws-admin superuser key' >>/target/root/.ssh/authorized_keys",
        'curl --data "vm=%s&token=%s" %s%s\n' %
            (vm.id, vm.token, settings.MAIN_DOMAIN, reverse(post_installation))
    ]

    profile += ('\nd-i preseed/late_command string %s' %
                (" && ".join(late_commands),))

    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'install',
        'vmid': vm.name,
        'profile': profile,
    }
    headers = {'Content-type': 'application/json'}
    try:
        response = json.loads(requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json",
                                            data=json.dumps(json_object), headers=headers).text)
    except Exception as e:
        raise install_vm.retry(exc=e)

    if response['result'] == 'Success':
        return True
    else:
        return on_vm_api_failure(json.dumps(json_object), response)


def get_vm_power_state(vm):
    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'get power state',
        'vmid': vm.name
    }
    headers = {'Content-type': 'application/json'}
    try:
        response = json.loads(requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json",
                                            data=json.dumps(json_object), headers=headers).text)
    except Exception as e:
        raise PlatformsAPINotWorkingException(e.message)

    if response['result'] == 'Success':
        if response['powerState'] == 'poweredOff':
            return "Off"
        elif response['powerState'] == 'poweredOn':
            return "On"
        else:
            pass  # TODO raise error
    else:
        pass  # TODO raise error


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def change_vm_power_state(vm, on):
    if on != 'on' and on != 'off':
        raise PlatformsAPIInputException("passed wrong parameter power %s" % on)

    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'power '+on,
        'vmid': vm.name
    }

    headers = {'Content-type': 'application/json'}
    try:
        response = json.loads(requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json",
                                            data=json.dumps(json_object), headers=headers).text)
    except Exception as e:
        raise change_vm_power_state.retry(exc=e)

    if response['result'] == 'Success':
        return True
    else:
        return on_vm_api_failure(json.dumps(json_object), response)


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def reset_vm(vm):
    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'reset',
        'vmid': vm.name
    }

    headers = {'Content-type': 'application/json'}
    r = requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json", data=json.dumps(json_object), headers=headers)
    try:
        response = json.loads(r.text)
    except Exception as e:
        raise reset_vm.retry(exc=e) # TODO are we sure we want to do that?

    if response['result'] == 'Success':
        return True
    else:
        return on_vm_api_failure(json.dumps(json_object), response)


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def destroy_vm(vm):
    change_vm_power_state(vm, "off")

    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'destroy',
        'vmid': vm.name
    }

    headers = {'Content-type': 'application/json'}
    r = requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json", data=json.dumps(json_object), headers=headers)
    try:
        response = json.loads(r.text)
    except Exception as e:
        raise destroy_vm.retry(exc=e)

    if response['result'] == 'Success':
        return True
    else:
        return on_vm_api_failure(json.dumps(json_object), response)


def clone_vm(site, primary_vm):
    delete_vm = None

    if primary_vm:
        original_vm = site.primary_vm
        if site.secondary_vm:
            delete_vm = site.secondary_vm
    else:
        original_vm = site.secondary_vm
        if site.primary_vm:
            delete_vm = site.primary_vm

    if delete_vm:
        delete_vm.site = None
        delete_vm.save()

    destination_vm = VirtualMachine.objects.create(primary=(not primary_vm), status='requested', token=uuid.uuid4(),
                                                   site=site, host_network_configuration =
                                                                HostNetworkConfig.get_free_config())
    clone_vm_api_call.delay(original_vm, destination_vm, delete_vm)


@shared_task(base=TaskWithFailure, default_retry_delay=5*60, max_retries=288) # Retry each 5 minutes for 24 hours
def clone_vm_api_call(orignal_vm, destination_vm, delete_vm):
    if delete_vm:
        delete_vm.delete()

    json_object = {
        'username': get_api_username(),
        'secret': get_api_secret(),
        'command': 'clone',
        'vmid': orignal_vm.name,
        'ip': destination_vm.ipv4,
        'hostname': destination_vm.hostname,
    }
    headers = {'Content-type': 'application/json'}
    try:
        response = json.loads(requests.post("https://bes.csi.cam.ac.uk/mws-api/v1/vm.json",
                                            data=json.dumps(json_object), headers=headers).text)
    except Exception as e:
        raise clone_vm_api_call.retry(exc=e)

    if response['result'] == 'Success':
        destination_vm.name = response['vmid']
        destination_vm.status = 'ready'
        destination_vm.save()

        # Copy Unix Groups
        for unix_group in orignal_vm.unix_groups.all():
            copy_users = unix_group.users.all()
            unix_group.pk = None
            unix_group.vm = destination_vm
            unix_group.save()
            unix_group.users = copy_users

        # Copy Ansible Configuration
        for ansible_conf in orignal_vm.ansible_configuration.all():
            ansible_conf.pk = None
            ansible_conf.vm = destination_vm
            ansible_conf.save()

        # Copy vhosts
        # TODO copy Domain Names
        for vhost in orignal_vm.vhosts.all():
            vhost.pk = None
            vhost.vm = destination_vm
            vhost.save()

        return True
    else:
        return on_vm_api_failure(json.dumps(json_object), response)
