# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesmanagement', '0077_auto_20170621_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
