# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesmanagement', '0078_auto_20171129_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='numcpu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='sizeram',
            field=models.IntegerField(default=1),
        ),
    ]
