# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesmanagement', '0079_auto_20180720_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='status',
            field=models.CharField(choices=[(b'requested', b'Requested'), (b'accepted', b'Accepted'), (b'private', b'Private'), (b'global', b'Global'), (b'external', b'External'), (b'special', b'Special'), (b'denied', b'Denied'), (b'deleted', b'Deleted')], default=b'requested', max_length=50),
        ),
    ]
